//lib/database/app_database.dart
import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

import 'tables/user_table.dart';
import 'daos/user_dao.dart';

import 'tables/user_profiles_table.dart';
import 'daos/user_profile_dao.dart';


import 'tables/product_table.dart';
import 'daos/product_dao.dart';
import 'tables/stock_movement_table.dart';
import 'daos/stock_movement_dao.dart';


import 'tables/supplier_table.dart';
import 'daos/supplier_dao.dart';

import 'tables/supplier_delivery_table.dart';
import 'tables/supplier_delivery_item_table.dart';
import 'tables/supplier_payment_table.dart';
import 'tables/supplier_payment_allocation_table.dart';


import 'daos/supplier_delivery_dao.dart';
import 'daos/supplier_delivery_item_dao.dart';
import 'daos/supplier_payment_dao.dart';
import 'daos/supplier_payment_allocation_dao.dart';


import 'tables/sales_table.dart';
import 'daos/sales_dao.dart';

import 'tables/settings_table.dart';
import 'daos/settings_dao.dart';

import 'tables/category_table.dart';   
import 'daos/category_dao.dart';       

import 'tables/attendance_table.dart';
import 'daos/attendance_dao.dart';

import 'tables/staff_purchase_table.dart';
import 'daos/staff_purchase_dao.dart';

import 'tables/staff_debt_payment_table.dart';
import 'daos/staff_debt_payment_dao.dart';

import 'tables/supplier_delivery_table.dart';
part 'app_database.g.dart'; 




// generated by build_runner

// single shared database instance 
AppDatabase? _instance;

AppDatabase getDatabase() {
  _instance ??= AppDatabase();
  return _instance!;
}

// single shared UserDao instance
UserDao? _userDao;

UserDao getUserDao() {
  _userDao ??= UserDao(getDatabase());
  return _userDao!;
}

// single shared UserDao instance
UserProfileDao? _userProfileDao;

UserProfileDao getUserProfileDao() {
  _userProfileDao ??= UserProfileDao(getDatabase());
  return _userProfileDao!;
}

// single shared ProductDao instance
ProductDao? _productDao;

ProductDao getProductDao() {
  _productDao ??= ProductDao(getDatabase());
  return _productDao!;
}

// single shared StockMovementDao instance
StockMovementDao? _stockMovementDao;

StockMovementDao getStockMovementDao() {
  _stockMovementDao ??= StockMovementDao(getDatabase());
  return _stockMovementDao!;
}
// single shared SupplierDao instance
SupplierDao? _supplierDao;

SupplierDao getSupplierDao() {
  _supplierDao ??= SupplierDao(getDatabase());
  return _supplierDao!;
}

//single shared SalesDao instance 
SalesDao? _salesDao;

SalesDao getSalesDao() {
  _salesDao ??= SalesDao(getDatabase());
  return _salesDao!;
}

//single shared SalesDao instance 
SettingsDao? _settingsDao;

SettingsDao getSettingsDao() {
  _settingsDao ??= SettingsDao(getDatabase());
  return _settingsDao!;
}

// single shared CategoryDao instance 
CategoryDao? _categoryDao;
CategoryDao getCategoryDao() => _categoryDao ??= CategoryDao(getDatabase());

// single shared AttendanceDao instance
AttendanceDao? _attendanceDao;
AttendanceDao getAttendanceDao() { 
  _attendanceDao ??= AttendanceDao(getDatabase());
  return _attendanceDao!;
}

// single shared StaffPurchaseDao instance
StaffPurchaseDao? _staffPurchaseDao;

StaffPurchaseDao getStaffPurchaseDao() {
  _staffPurchaseDao ??= StaffPurchaseDao(getDatabase());
  return _staffPurchaseDao!;
}

// single shared StaffDebtPaymentDao instance
StaffDebtPaymentDao? _staffDebtPaymentDao;

StaffDebtPaymentDao getStaffDebtPaymentDao() {
  _staffDebtPaymentDao ??= StaffDebtPaymentDao(getDatabase());
  return _staffDebtPaymentDao!;
}


//single shared SupplierDeliveryDao instance
SupplierDeliveryDao? _supplierDeliveryDao;

SupplierDeliveryDao getSupplierDeliveryDao() {
  _supplierDeliveryDao ??=
      SupplierDeliveryDao(getDatabase());

  return _supplierDeliveryDao!;
}

//single shared SupplierDeliveryItemDao instance
SupplierDeliveryItemDao? _supplierDeliveryItemDao;

SupplierDeliveryItemDao getSupplierDeliveryItemDao() {
  _supplierDeliveryItemDao ??=
      SupplierDeliveryItemDao(getDatabase());

  return _supplierDeliveryItemDao!;
}

//single shared SupplierPaymentDao instance
SupplierPaymentDao? _supplierPaymentDao;

SupplierPaymentDao getSupplierPaymentDao() {
  _supplierPaymentDao ??=
      SupplierPaymentDao(getDatabase());

  return _supplierPaymentDao!;
}

//single shared SupplierPaymentAllocationDao instance
SupplierPaymentAllocationDao? _supplierPaymentAllocationDao;

SupplierPaymentAllocationDao getSupplierPaymentAllocationDao() {
  _supplierPaymentAllocationDao ??=
      SupplierPaymentAllocationDao(getDatabase());

  return _supplierPaymentAllocationDao!;
}


@DriftDatabase(
  tables: [Users, Products, StockMovements, Suppliers, Sales, Settings, Categories, UserProfiles, Attendance, StaffPurchases, StaffDebtPayments, 
            SupplierDeliveries, SupplierDeliveryItems, SupplierPayments, SupplierPaymentAllocations,],

  daos: [UserDao, ProductDao, StockMovementDao, SupplierDao, SalesDao, SettingsDao, CategoryDao, UserProfileDao, AttendanceDao, StaffPurchaseDao, StaffDebtPaymentDao,
         SupplierDeliveryDao, SupplierDeliveryItemDao, SupplierPaymentDao, SupplierPaymentAllocationDao,],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 24; // bump version when schema changes

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async {
          await m.createAll(); // create all tables on fresh install
        
        },
        onUpgrade: (m, from, to) async {
          if (from <= 1) {
            // upgrading from schema v1 → v2
            await m.createTable(products);
          }
          if (from <= 2) {
            // upgrading from schema v2 → v3
            await m.createTable(stockMovements);
          }
          if (from <= 3) {
            // upgrading from schema v3 → v4
            await m.createTable(suppliers);
          }
          if (from <= 4) {
            // upgrading from schema v4 → v5
            await m.createTable(sales);
          }

          if (from <= 5) {
            await m.addColumn(sales, sales.paymentMethod);
            await m.addColumn(sales, sales.cashAmount);
            await m.addColumn(sales, sales.transferAmount);
          }

          if (from <= 6) {
            await m.addColumn(products, products.stock); // ✅ new stock column
          }

          if (from <= 7) {
            // upgrading from schema v5 → v6
            await m.createTable(settings);
          }

          if (from <=8) {
            await m.createTable(categories);
          }

          if (from <= 10) {
            await m.addColumn(sales, sales.staffId);
          }

          if (from <=11) {
            await m.createTable(userProfiles);
          }

          if (from <= 15) {
            await customStatement('''
              UPDATE sales
              SET cost_price_at_sale = (
                SELECT cost_price
                FROM products
                WHERE products.id = sales.product_id
              )
              WHERE cost_price_at_sale = 0
            ''');
          }

          // Schema 16 → 17
          if (from <= 16) {
            await m.addColumn(users, users.loginId);

            // Give existing users a login ID based on their existing ID.
          await customStatement('''
            UPDATE users
            SET login_id = 'USER' || printf('%04d', id)
            WHERE login_id IS NULL
          ''');
          }

          if (from <= 17) {
            await m.addColumn(users, users.isActive);
          }

          if (from <= 18) {
            await m.createTable(attendance);
          }

          // v19 → v20
          if (from <= 19) {
            await m.addColumn(
              attendance,
              attendance.correctedByUserId,
            );

            await m.addColumn(
              attendance,
              attendance.correctedAt,
            );

            await m.addColumn(
              attendance,
              attendance.correctionNote,
            );
          }

          // SCHEMA 20 → 21 // STAFF PURCHASES 
          if (from <= 20) { 
            await m.createTable(staffPurchases); 
          }

          // SCHEMA 21 → 22 // STAFF PURCHASES 
          if (from <= 21) { 
            await m.createTable(staffDebtPayments); 
          }


          // ============================================================
          // SCHEMA 22 → 23
          // SUPPLIER PAYABLES
          // ============================================================

          if (from <= 22) {
            // Supplier deliveries must exist before delivery items
            // because delivery items reference supplier deliveries.
            await m.createTable(supplierDeliveries);

            // Individual products received in each delivery.
            await m.createTable(supplierDeliveryItems);

            // Actual payments made to suppliers.
            await m.createTable(supplierPayments);

            // Connect payments to one or more supplier deliveries.
            await m.createTable(supplierPaymentAllocations);
          }

          // SCHEMA 23 → 24
          // LINK STOCK MOVEMENTS TO SUPPLIER DELIVERIES

          if (from <= 23) {
            await m.addColumn(
              stockMovements,
              stockMovements.deliveryId,
            );
          }
                  
        
          // if you add more versions later, handle them here
        },
      );
}


// Lazy database connection
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    print("✅ Database folder path: ${dbFolder.path}");
    final file = File(p.join(dbFolder.path, 'supermarket.sqlite'));
    return NativeDatabase(file);
  });
}
